name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.x'
        channel: 'stable'
    # Get flutter dependencies.
    - run: flutter pub get
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    # Run all the tests.
    - run: flutter test